name: Upload a Build Artifact

on:
  push:
    branches: [seolroh]
  pull_request:
    branches: [seolroh]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '10.15.1'
          node-version-file: '.node-version'
    # Artifact name
      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: target
          retention-days: 1